site_name: HyperRetailCloud StartUp Level 1
site_url: https://ivanrobuschi-custom.github.io/hypercloud_level_1/
site_author: Custom S.p.A.

theme:
  name: material
  logo: assets/icons/logo.png
  favicon: assets/icons/favicon.png
  language: it
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list

plugins:
  - search
  - tags

copyright: Copyright Custom S.p.A 2026

nav:
  - Introduzione: index.md
  - "Gestione Licenze": cap1_hyperland.md
  - "Anagrafiche e Schermate": cap2_anagrafiche.md
  - "Primo Accesso e Configurazione":
    - cap3_primo_accesso.md
    - tutorial_articoli_reparti.md
  - "Avvio Software e Anagrafiche": cap4_avvio_software.md
  - "Primo Documento Commerciale": cap5_primo_scontrino.md
  - "Azzeramento Fiscale": cap6_azzeramento.md
